// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Rocket$Type } from "./Rocket";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Rocket"]: Rocket$Type;
    ["contracts/Rocket.sol:Rocket"]: Rocket$Type;
  }
}
